Update of Guzzle dependency & overall code clean up
Unbabel/unbabel-php pull request #6
Opened 2018-06-03 15:43 UTC by stloyd

This PR replaces old & not maintained Guzzle 3 dependency with supported version 6.x and also removed useless proxy code of HTTP client.

Additionally I have reworked the code to better match i.e. PSR-4, simplified it when possible, fixed examples in code & README.

2018-06-06 17:16 UTC, andreffs18 commented
Hey @stloyd, I was trying the new example on the #Usage part on the README file and I'm getting this error:

![image](https://user-images.githubusercontent.com/5011530/41052370-7e87979a-69b0-11e8-8702-1cf56986b3d9.png)

To solve this I've updated my PHP to 7.0.27. Did you tried this new version on 5.6 with success? If not maybe it's better to remove the 5.6 from the Requirements.

2018-06-06 17:17 UTC, andreffs18 commented
Other than that everything seems very good! Great job! 👍

2018-06-07 06:48 UTC, stloyd commented
@andreffs18 Right, I was doing this on PHP 7.x. In fact I guess this PR can drop support for version PHP 5.6 as this version is not maintained anymore at all (and get's only security fixes till end of 2018 - http://php.net/supported-versions.php ). WDYT?

2018-06-07 14:31 UTC, andreffs18 commented
I agree! Except for the requirement on the README file and a couple of other small things I can't find anything that's not okay. I'll go ahead and review this so we can them merge it afterwards.

2018-06-07 14:39 UTC, andreffs18 requested changes
Just some minor changes. 
Great stuff! 👍🚀

2018-06-07 14:39 UTC, andreffs18 commented on README.md
> +* PHP: 5.6 / 7.x
Since this version is not compatible with 5.6, we should remove it from here.

2018-06-07 14:39 UTC, andreffs18 commented on README.md
> +     false, // call sandbox?
Does this comment specify that we should not call sandbox? It would be better to have a variable like `callSandbox = false;` or no comment at all.

2018-06-07 14:39 UTC, andreffs18 commented on README.md
> +$opts = array('callback_url' => 'http://my-awesome-app/unbabel_callback.php');
The url is invalid. The ".com" is missing. Running this example like it is will return a HTTP 400 Bad request.

2018-06-07 14:39 UTC, andreffs18 commented on README.md
> +   // send email to sam@unbabel.com to complain.
Update the email to **tech-support@unbabel.com**

2018-06-07 14:39 UTC, andreffs18 commented on composer.json
> +        "php": "^5.6 || ^7.0",
Remove the 5.6 from the requirements

2018-06-07 14:39 UTC, andreffs18 commented on composer.json
>              "email": "sam@unbabel.com"
Just an email is okay. We can use "tech-support@unbabel.com".

2018-06-08 09:09 UTC, stloyd commented
@andreffs18 Done, should be correct now.

2018-06-08 09:58 UTC, andreffs18 approved these changes

2018-06-08 09:58 UTC, merged